[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/thank-you/"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/careers"
  to = "/careers.html"
  status = 200

[[redirects]]
  from = "/careers/"
  to = "/careers.html"
  status = 200

